services:
  ta4j_sc_mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      TZ: Europe/Zurich
      MYSQL_ROOT_PASSWORD: ${TA4J_SC_MYSQL_ROOT}
      MYSQL_DATABASE: ta4j_showcase
      MYSQL_USER: ${TA4J_SC_MYSQL_USER}
      MYSQL_PASSWORD: ${TA4J_SC_MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app_network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  ta4j_app:
    build: .
    container_name: ta4j_app
    restart: on-failure
    depends_on:
      ta4j_sc_mysql:
        condition: service_healthy
    environment:
      TZ: Europe/Zurich
      SPRING_DATASOURCE_URL: jdbc:mysql://ta4j_sc_mysql:3306/ta4j_showcase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${TA4J_SC_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${TA4J_SC_MYSQL_PASSWORD}
      TA4J_TG_BOT_NAME: ${TA4J_TG_BOT_NAME}
      TA4J_TG_BOT_PW: ${TA4J_TG_BOT_PW}
      BINANCE_DEMO_API_KEY: ${BINANCE_API_KEY}
      BINANCE_DEMO_API_SECRET: ${BINANCE_API_SECRET}
    volumes:
      - /opt/ta4j_showcase/logs:/app/logs
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge