spring.application.name=ts4j-showcase

spring.datasource.url=jdbc:mysql://localhost:3308/ts4j_showcase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${TS4J_SC_MYSQL_USER}
spring.datasource.password=${TS4J_SC_MYSQL_PASSWORD}
