spring.application.name=ta4j-showcase

spring.datasource.url=jdbc:mysql://localhost:3308/ta4j_showcase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${TA4J_SC_MYSQL_USER}
spring.datasource.password=${TA4J_SC_MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Telegram Bot Starter properties
bot.name=${TA4J_TG_BOT_NAME}
bot.token=${TA4J_TG_BOT_PW}

# Percentage of the user account balance in the commission asset.
# Ranges between 0 and 100. A value of 5 means: the value of a new position is equal to 5% of the account balance
# (of USDT for instance).
trade.position.size-percentage=5
trade.position.commission-asset=USDT
# Comma-separated list of strategy configurations to load. Every loaded strategy will be executed using the configuration defined in the given file.
# The files must be in JSON format, and the file ending must be ".json". Providing the file ending in this list is optional.
# Configuration files must all remain in the directory: src/main/resources/strategy/configuration.
trade.strategy.create=EmaCrossConfiguration-test-btc-max-trades, EmaCrossConfiguration-test-eth-max-trades, EmaCrossConfiguration-test-bnb-max-trades

trade.api.url=https://demo-fapi.binance.com
trade.api.websocket.url=wss://fstream.binancefuture.com

# Binance API credentials (demo)
# Note that these credentials must be created in the demo account (https://demo.binance.com), not the real one.
# Using any real API key will result in a 401 Unauthorized error.
binance.api.key=${BINANCE_DEMO_API_KEY}
binance.api.secret=${BINANCE_DEMO_API_SECRET}
