spring.application.name=ts4j-showcase

spring.datasource.url=jdbc:mysql://localhost:3308/ts4j_showcase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${TS4J_SC_MYSQL_USER}
spring.datasource.password=${TS4J_SC_MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Telegram Bot Starter properties
bot.name=${TS4J_TG_BOT_NAME}
bot.token=${TS4J_TG_BOT_PW}

# Binance API credentials (demo)
# Note that these credentials must be created in the demo account (https://demo.binance.com), not the real one.
# Using any real API key will result in a 401 Unauthorized error.
binance.demo.api.key=${BINANCE_DEMO_API_KEY}
binance.demo.api.secret=${BINANCE_DEMO_API_SECRET}

binance.use-real-api=false