networks:
  app_network:
    driver: bridge

services:
  ts4j_sc_mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TS4J_SC_MYSQL_ROOT}
      MYSQL_DATABASE: ts4j_showcase
      MYSQL_USER: ${TS4J_SC_MYSQL_USER}
      MYSQL_PASSWORD: ${TS4J_SC_MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app_network
    env_file:
      - .env